---
version: '3.8'
services:
   mydb:
      image: postgres
      environment:
         POSTGRES_PASSWORD: mvbrothers
         POSTGRES_USER: myuser
         POSTGRES_DB: mydb
   myadminer:
      image: adminer
      ports:
         - 9090:8080
networks:
   default:
      external:
         name: ravindra
...


