version: '3.8'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mywordpress
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mvbrothers
      WORDPRESS_DB_NAME: ravindra
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser1
      MYSQL_PASSWORD: mvbrothers
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
