---
version: '3.8'
services:
   mydb: 
      image: mysql:5
      environment:
         MYSQL_ROOT_PASSWORD: mvbrothers
   mywordpress: 
      image: wordpress
      ports: 
        - 8080:80
      links: 
        - mydb:mysql
...
